bo_homepage:
    path: /
    defaults: { _controller: 'App\Controller\BoController::index' }
    methods: GET

bo_login:
    path: /login
    defaults: { _controller: 'App\Controller\BoController::login' }
    methods: GET

bo_login_post:
    path: /login
    defaults: { _controller: 'App\Controller\BoController::loginPost' }
    methods: POST

bo_simpleform:
    path: /simpleform
    defaults: { _controller: 'App\Controller\BoController::simpleform' }
    methods: GET

bo_advancedform:
    path: /advancedform
    defaults: { _controller: 'App\Controller\BoController::advancedform' }
    methods: GET